# Generated by Django 5.2.1 on 2025-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
