# Generated by Django 5.2.1 on 2025-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
