# Generated by Django 5.2.1 on 2025-07-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_contactinfo_address_alter_contactinfo_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandmember",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
