# Generated by Django 5.2.4 on 2025-07-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_bandmember_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
