# Generated by Django 5.2.4 on 2025-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_contactinfo_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.TextField(blank=True, null=True),
        ),
    ]
