# Generated by Django 5.2.4 on 2025-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_event_date_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
