# Generated by Django 5.2.4 on 2025-07-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_event_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchandise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="merchandise/"),
                ),
            ],
        ),
    ]
