# Generated by Django 5.2.4 on 2025-07-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_merchandise"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the media item",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image/Album Cover"),
                            ("video_file", "Video File"),
                            ("video_link", "Video Link (YouTube/Vimeo)"),
                        ],
                        help_text="Type of media content",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image or album cover",
                        null=True,
                        upload_to="media/images/",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a video file (MP4, WebM, etc.)",
                        null=True,
                        upload_to="media/videos/",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        help_text="YouTube, Vimeo, or other video link",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for displaying items (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Media Item",
                "verbose_name_plural": "Media Items",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
