# Generated by Django 5.2.4 on 2026-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload an audio file (MP3, WAV, M4A, OGG, FLAC)', null=True, upload_to='media/audio/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image/Album Cover'), ('audio', 'Audio Track'), ('video_file', 'Video File'), ('video_link', 'Video Link (YouTube/Vimeo)')], help_text='Type of media content', max_length=20),
        ),
    ]
